### PR TITLE
Worktrees implementation

### PR DESCRIPTION
**Pull request by rmedaer**
I **started** to implement Python binding for worktrees management.
 
Added the following features:
  - Add a new worktree: Repository#add_worktree(name, path) -> None
  - List existing worktrees: Repository#list_worktrees() -> [string]

### CODE REVIEW

**Comment by jdavid** [comment]
Hi @rmedaer 
Merging will have to wait for a release of libgit2 with ``git_worktree_*``
Could you add some unit tests?

**Comment by rmedaer** [comment]
@jdavid no problem, I can wait. Btw, I'm adding a new PyObject Worktree to implement all the features (prune, lock, unlock).

Actually my first commit was a test.
Of course, once it's implemented I can add some unit tests ! ;-)

**Comment by pks-t** [comment]
@rmedaer Are there any comments regarding the C API itself? The implementation is obviously still very new and I'd like to weed out design smells before it hits the first release

**Comment by rmedaer** [comment]
@pks-t I didn't find any documentation [here](https://libgit2.github.com/libgit2/#HEAD). However there is some comments about [available functions](https://github.com/libgit2/libgit2/blob/4f9f8e0dc9ca8a912fe1b32aeca545d25790d3fe/include/git2/worktree.h) and [worktree structure](https://github.com/libgit2/libgit2/blob/4f9f8e0dc9ca8a912fe1b32aeca545d25790d3fe/src/worktree.h).

I guess, goal of libgit2 developer is to reproduce the same API calls then Git commands. Check out the track here: https://github.com/libgit2/libgit2/pull/3436

**Comment by jdavid** [comment]
Hi @rmedaer 
There are conflicts merging this, could you please rebase?
Thanks!

**Comment by jdavid** [comment]
This was superseded by #719

**Pull request closed without merging**
