### PR TITLE
Add update_submodule method in Repository class.

### PR DESCRIPTION
**Pull request by zhangyiant**

### CODE REVIEW

**Comment by jdavid** [comment]
How is this different from ``Repository.update_submodules`` ?
See https://github.com/libgit2/pygit2/blob/master/src/repository.c#L1360 and http://www.pygit2.org/submodule.html?highlight=update_submodules#pygit2.Repository.update_submodules

**Comment by jdavid** [comment]
If the purpose is to type:

    repo.update_submodule(submodule)

Instead of:

    repo.update_submodules([submodule])

I would rather have a single method which accepts both:

    repo.update_submodules(submodule)
    repo.update_submodules([submodule])

Feel free to replace the ``repo.update_submodules`` written in C by one using cffi, which is backwards compatible and accepts a singleton.

Thanks for your PR!

**Comment by zhangyiant** [comment]
The initial intent is to update `submodule` with credential input which is not supported in current `update_submodules` method.
Yes, I agree your suggestion to have a single method. I'll update the PR when it's ready.

**Comment by zhangyiant** [comment]
Close this pull request.
A new pull request will be opened, which will replace current C version update_submodules.

**Pull request closed without merging**
