### PR TITLE
Add more tests to test_patch and test_blob

### PR DESCRIPTION
**Pull request by brandonio21**
As reported in #754 , there are some strange corruption-looking things happening with creating patches. In order to find strange behavior, I've crafted the tests attached to this PR. 

At the time of writing, I could only get one of the tests to reliably fail: **test_patch_multi_blob**

```
Traceback (most recent call last):
  File "/home/engshare/third-party2/pygit2/0.26.2/src/build-gcc-5-glibc-2.23/pic/test/test_patch.py", line 231, in test_patch_multi_blob
    self.assertEqual(patch_text, [patch.patch for patch in patches])
AssertionError: Lists differ: [u'diff --git a/file b/file\nd... != [u'diff --git a/file b/file\nd...

First differing element 0:
diff --git a/file b/file
deleted file mode 100644
index a520c24..0000000
--- a/file
+++ /dev/null
@@ -1,3 +0,0 @@
-hello world
-hola mundo
-bonjour le monde

diff --git a/file b/file
deleted file mode 100644
index a520c24..0000000
--- a/file
+++ /dev/null
@@ -1,3 +0,0 @@
-@^H05

Diff is 11160 characters long. Set self.maxDiff to None to see it.
```

I don't think this PR should be merged in until the problem is fixed.

### CODE REVIEW

**Comment by brandonio21** [comment]
YES! I FINALLY GOT THE BUG TO REPRO ON CI! LIFE IS GOOD!

**Comment by brandonio21** [comment]
Going to rebase this

**Comment by jdavid** [comment]
yes please

**Comment by brandonio21** [comment]
@jdavid : It's ready to be merged in! Let's do it!

**Comment by jdavid** [comment]
thanks!

**Pull request merged**
