### PR TITLE
Add git-cherry-pick recipe

### PR DESCRIPTION
**Pull request by rmoehn**
Add the way that worked for me. Not sure if it is idiomatic.

### CODE REVIEW

**Comment by jdavid** [comment]
just merged PR #492 which adds ``Repository.cherrypick()``

**Comment by rmoehn** [comment]
Haha, well, that makes it easier then. Does my recipe still have a place somewhere? I mean, it allows for more finegrained control and demonstrates how one could use `merge_trees()`.

**Comment by rmoehn** [comment]
Plus it lets you do a cherry-pick without a checkout.

**Comment by jdavid** [comment]
Best thing would be to show first the higher level interface, and last the advanced usage.

**Comment by carlosmn** [comment]
Note that what you're doing here isn't a cherry-pick but a straight merge. Cherry-pick should have the commit's parent as the merge-base.

**Comment by rmoehn** [comment]
Ah ok, good to know. But which commit's parent? The cherry's or the basket's?

So maybe I'll write a section about how to use the new cherry-pick facility, then what I wrote with the merge-base fixed and possibly a note that you can do other strange things. I don't have time for that right now, but will do it next weekend, I guess. So don't delete the pull request yet. :-)

**Comment by carlosmn** [comment]
A cherry-pick means applying a commit's (implicit) diff on top the current commit, so you have to get the cherry and its parents to create the diff. It's not too different from `git show <cherry> | git apply -` (if they accepted the same format).

**Comment by rmoehn** [comment]
Hmm, I didn't want to close this. Apparently I messed up things again by force-pushing or something. It would be cool if one could fork one's own repos to try what effects various actions have on pull requests. I could open another account for that…

Anyway, I wrote a recipe with both ways of cherry-picking, but when I try this, my repo remains in cherry-picking mode afterwards:

    basket = repo.lookup_branch('basket')
    repo.checkout(basket)

    cherry = repo.get('17513e5954')
    repo.cherrypick(cherry.oid)

    if repo.index.conflicts is None:
        tree_id = repo.index.write_tree()

        committer = pygit2.Signature('Archimedes', 'archy@jpl-classics.org')

        repo.create_commit(basket.name, cherry.author, committer,
                        cherry.message, tree_id, [basket.target])
        basket = None # outdated, prevent from accidentally using it

Am I failing to do something I should do, but which the docs on `Repository.cherrypick()` don't tell me about?

**Pull request closed without merging**
