### PR TITLE
Allow setting merge options in Repository.merge

### PR DESCRIPTION
**Pull request by olsen232**
Up to now, Repository.merge_commits and Repository.merge_trees only
allowed the caller to choose the file_favor. This change also
allows them to set or unset any of the merge_flags or merge_file_flags,
while preserving the default behavior.

### CODE REVIEW

**Comment by olsen232** [comment]
(@rcoup asked to be cc'd on all pygit2 PRs by koordinates staff)

**Comment by olsen232** [comment]
@rcoup I am not familiar with this repository - can you make sure that the right reviewer sees this?

**Comment by rcoup** [comment]
@jdavid has looked at all mine, but his time varies a bit.

@olsen232 LGTM though. Can we add/expand tests for `_merge_options()`/`_flag_dict_to_bitmask()` — the rest prettymuch gets passed verbatim to libgit2, doesn't seem helpful.

**Comment by jdavid** [comment]
correct, there are no tests

**Comment by olsen232** [comment]
@jdavid @rcoup added tests

**Pull request merged**
