### PR TITLE
Fix testing manylinux1 wheels

### PR DESCRIPTION
**Pull request by webknjaz**

### CODE REVIEW

**Comment by webknjaz** [comment]
Here's the build log: https://travis-ci.com/webknjaz/pygit2/jobs/181669779

**Comment by webknjaz** [comment]
@jdavid CI test failures are unrelated and existed in master earlier.

BTW could you please enable CRON in Travis CI?

**Comment by jdavid** [comment]
Do you want to add a cron job to run a build on master periodically? daily, weekly, monthly?
Which is the purpose?

**Comment by webknjaz** [comment]
Purpose is that it could run additional heavy jobs + ensure that dependencies are healthy.

**Comment by jdavid** [comment]
added: master, weekly, do not run if there has been a build in the last 24h

**Comment by webknjaz** [comment]
In this case it won't run jobs which only run on cron sometimes.

**Comment by jdavid** [comment]
ok changed to always run

**Pull request merged**
