### PR TITLE
Attempt to fix test on Windows

### PR DESCRIPTION
**Pull request by techtonik**
Close index to allow directory removal there (#655)

### CODE REVIEW

**Comment by techtonik** [comment]
@jdavid this needs more serious debugging - https://ci.appveyor.com/project/techtonik/pygit2 - it looks like the problem might be in C level. Index open and closed correctly, and even though it is not clear why it happens 6 times instead of 3, it looks like C level doesn't close the handle. Can you check this with `ptrace` or with `lsof` at the end of archive test?

**Comment by techtonik** [comment]
I can't run `gitless` because of this and run of of time to debug the issue.

**Comment by carlosmn** [comment]
You cannot get this kind of error due to `Index`. The file is closed as soon as the contents are read, and IIRC it's closed even before we start parsing the contents.

What does stay open (and it's what the AppVeyor logs show) are the packfile indices. These are kept open since we memory-map them since they're read-only and are potentially large. In order to close those handles, you need to make sure to free the underlying `git_repository`, which means making sure any `Repository` instances get garbage-collected.

You will then have to work around the object db being made out of read-only files, as Windows won't let you delete them normally, and it's usually a pain to deal with in test suites.

But fixing this in the test suite isn't going to fix anything else using pygit2. Whatever tool you're using must make sure to release its `Repository` instances on Windows if you want to delete repositories while the program is still running.

**Comment by jdavid** [comment]
Thanks for the explanation @carlosmn 

I have merged branch fourplusone/fix/windows-tests from @fourplusone and errors are down to 7 from 146 ... but the build is green, @fourplusone ?

Closing this PR.

**Pull request closed without merging**
