### PR TITLE
mitigate python3 import error

### PR DESCRIPTION
**Pull request by ThePsyjo**
I think it can be made better, but this one works so far for me. NOT tested with anything but 3.4.2 @ Debian Jessie !

> ImportError: No module named '_build'

### CODE REVIEW

**Comment by jdavid** [comment]
The tests fail.

Which is the problem you are trying to fix?

**Comment by ThePsyjo** [comment]
Hi,

I know that tests fail. I Wrote the error in the initial comment:

> ImportError: No module named '_build'

I fixed it on the server in question by just appending the dot in front of the module and it worked. As I wrote: it can certainly be made better than this, but I'm currently unable to proper test this.

**Comment by jdavid** [comment]
I do not understand what you are trying to fix. Currently the tests pass on the master branch, for all supported versions of Python, including Python 3, see https://travis-ci.org/libgit2/pygit2

Can you give an scenario to reproduce the error you are trying to fix?

**Comment by ThePsyjo** [comment]
It just does not work as it is in Debian Jessie.

It happend when I do this

`from pygit2 import clone_repository, Repository`

And the exceptions are this:

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/pygit2/ffi.py", line 33, in <module>
    from ._libgit2 import ffi, lib as C
ImportError: No module named 'pygit2._libgit2'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
...
  File "/usr/local/lib/python3.4/dist-packages/pygit2/__init__.py", line 35, in <module>
    from .blame import Blame, BlameHunk
  File "/usr/local/lib/python3.4/dist-packages/pygit2/blame.py", line 32, in <module>
    from .errors import check_error
  File "/usr/local/lib/python3.4/dist-packages/pygit2/errors.py", line 29, in <module>
    from .ffi import ffi, C
  File "/usr/local/lib/python3.4/dist-packages/pygit2/ffi.py", line 35, in <module>
    from ._run import ffi, preamble, C_KEYWORDS
  File "/usr/local/lib/python3.4/dist-packages/pygit2/_run.py", line 42, in <module>
    from _build import get_libgit2_paths
ImportError: No module named '_build'

```

When change 
`from _build import get_libgit2_paths`
to
`from ._build import get_libgit2_paths`
It works.

Environment:

Debian Jessie (8.2)

python3.4  3.4.2-1 (dpkg)
pygit2  0.24.1 (pip)

**Comment by joshm91** [comment]
I'm seeing the same issue when trying to import pygit2 in an AWS Lambda instance running Python 3.6.  The same import works correctly on my local machine (OSX 10.11.6) running the same Python version.

The proposed fix solves the problem.

**Comment by joshm91** [comment]
The error actually just disappeared for me... The package I'm uploading to Lambda is just using v0.26.3 and the import error stopped happening. Thanks though!

**Comment by jdavid** [comment]
Ok.

**Pull request closed without merging**
